### PR TITLE
Added github key property

### PR DESCRIPTION
**Pull request by zwall-bp**
A quick patch to implement the automatic configuration and deployment of a Github secret key, in the event Github is needed for in Hookshot.

### CODE REVIEW

**Review by ramereth — APPROVED** [review]
minor bump

**Comment by zwall-bp** [comment]
!bump minor

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.1.0.  Have a nice day!

**Comment by ramereth** [comment]
> !bump minor

You forgot to add `~` at the end FWIW.

**Pull request merged**
